[functions]
    directory = "functions"

[functions."verify-turnstile"]
    node_bundler = "esbuild"
    node_version = "18"

[functions."check-verified"]
    node_bundler = "esbuild"
    node_version = "18"